[workspace]
members = [
    "coreutils",
    "bin/cat", 
    "bin/clear", 
    "bin/echo", 
    "bin/date", 
    "bin/false", 
    "bin/ls", 
    "bin/pwd", 
    "bin/true", 
    "bin/uname", 
    "bin/whoami",
    "bin/yes",
]
resolver = "3"
